###Server api
@rootURL = http://localhost:8000
@apiEp  = {{rootURL}}/api/v1

###check the ep server status
GET {{apiEp}}/


###check the root server status
GET {{rootURL}}/    

###check the ep server status
GET {{apiEp}}/users
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE3MTYyNTc1MDIsImV4cCI6MTcxNjI1ODQwMn0.SKZJLwq1oyisz9T6RsHUCnlqdEpE8ILr0hpOF04R4hQ

###check the invalid server status
GET {{rootURL}}/

###check the invalid server status
GET {{apiEp}}/sdffdsds



### Post user 
POST {{apiEp}}/users
Content-Type: application/json

{
    "fname": "sujan",
    "lname": "thapa",
    "phone": "234345345",
    "email": "asdf@sdfc.com",
    "password": "sdfdsf"
  
}